// <auto-generated />
using System;
using IIIF.POC.PostgreSqlRelationalV3Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IIIF.POC.PostgreSqlRelationalV3Store.Migrations
{
    [DbContext(typeof(ManifestStoreDbContext))]
    [Migration("20260805185410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IIIF.POC.PostgreSqlRelationalV3Store.Domain.ManifestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CanvasCount")
                        .HasColumnType("integer")
                        .HasColumnName("canvas_count");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IiifId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("list_iiif_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("list_label");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_version");

                    b.Property<int>("StructureCount")
                        .HasColumnType("integer")
                        .HasColumnName("structure_count");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_manifests");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_manifests_hash");

                    b.HasIndex("IiifId")
                        .IsUnique()
                        .HasDatabaseName("ux_manifests_iiif_id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_manifests_updated_at");

                    b.ToTable("manifests", (string)null);
                });

            modelBuilder.Entity("IIIF.POC.PostgreSqlRelationalV3Store.Domain.ManifestEntity", b =>
                {
                    b.OwnsOne("IIIF.Manifests.Serializer.Nodes.Manifest", "Manifest", b1 =>
                        {
                            b1.Property<Guid>("ManifestEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccompanyingCanvas")
                                .HasColumnType("jsonb")
                                .HasColumnName("manifest_accompanying_canvas");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("context");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("iiif_id");

                            b1.Property<string>("Items")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("items");

                            b1.Property<DateTime?>("NavDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("nav_date");

                            b1.Property<string>("PlaceholderCanvas")
                                .HasColumnType("jsonb")
                                .HasColumnName("placeholder_canvas");

                            b1.Property<string>("Rights")
                                .HasColumnType("text")
                                .HasColumnName("rights");

                            b1.Property<string>("Start")
                                .HasColumnType("jsonb")
                                .HasColumnName("start");

                            b1.Property<string>("Type")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("type");

                            b1.Property<string>("ViewingDirection")
                                .HasColumnType("text")
                                .HasColumnName("viewing_direction");

                            b1.HasKey("ManifestEntityId");

                            b1.HasIndex("Items")
                                .HasDatabaseName("ix_manifests_items_gin");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Items"), "gin");

                            b1.ToTable("manifests");

                            b1.WithOwner()
                                .HasForeignKey("ManifestEntityId");

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.Behavior", "Behavior", b2 =>
                                {
                                    b2.Property<Guid>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("row_id");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("value");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RowId");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_behavior", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.Homepage", "Homepage", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Format")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("format");

                                    b2.Property<string>("Label")
                                        .HasColumnType("text")
                                        .HasColumnName("label");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_homepage", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.Label", "Label", b2 =>
                                {
                                    b2.Property<Guid>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("row_id");

                                    b2.Property<string>("Language")
                                        .HasMaxLength(35)
                                        .HasColumnType("character varying(35)")
                                        .HasColumnName("language");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("value");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RowId");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_labels", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsOne("IIIF.Manifests.Serializer.Properties.Logo", "Logo", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Format")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("format");

                                    b2.Property<int?>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("height");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<int?>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("width");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id")
                                        .IsUnique();

                                    b2.ToTable("manifest_logo", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.MetadataProperty.Metadata", "Metadata", b2 =>
                                {
                                    b2.Property<string>("Label")
                                        .HasColumnType("text")
                                        .HasColumnName("label");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Label");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_metadata", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.MetadataProperty.MetadataValue.MetadataValue", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Language")
                                                .HasMaxLength(35)
                                                .HasColumnType("character varying(35)")
                                                .HasColumnName("language");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<string>("metadata_label")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("metadata_label");

                                            b3.ToTable("manifest_metadata_values", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("metadata_label");
                                        });

                                    b2.Navigation("Value");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.PartOf", "PartOf", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_part_of", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.Provider", "Provider", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Format")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("format");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_provider", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Homepage", "Homepage", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<string>("Label")
                                                .HasColumnType("text")
                                                .HasColumnName("label");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("provider_id")
                                                .IsRequired()
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("provider_id");

                                            b3.ToTable("manifest_provider_homepages", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("provider_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Label", "Label", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Language")
                                                .HasMaxLength(35)
                                                .HasColumnType("character varying(35)")
                                                .HasColumnName("language");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<string>("provider_id")
                                                .IsRequired()
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("provider_id");

                                            b3.ToTable("manifest_provider_labels", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("provider_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Logo", "Logo", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<int?>("Height")
                                                .HasColumnType("integer")
                                                .HasColumnName("height");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<int?>("Width")
                                                .HasColumnType("integer")
                                                .HasColumnName("width");

                                            b3.Property<string>("provider_id")
                                                .IsRequired()
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("provider_id");

                                            b3.ToTable("manifest_provider_logos", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("provider_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.SeeAlso", "SeeAlso", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<string>("Label")
                                                .HasColumnType("text")
                                                .HasColumnName("label");

                                            b3.Property<string>("Profile")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("profile");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("provider_id")
                                                .IsRequired()
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("provider_id");

                                            b3.ToTable("manifest_provider_see_also", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("provider_id");
                                        });

                                    b2.Navigation("Homepage");

                                    b2.Navigation("Label");

                                    b2.Navigation("Logo");

                                    b2.Navigation("SeeAlso");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.Rendering", "Rendering", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Format")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("format");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("label");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_rendering", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsOne("IIIF.Manifests.Serializer.Properties.RequiredStatement", "RequiredStatement", b2 =>
                                {
                                    b2.Property<Guid>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("row_id");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RowId");

                                    b2.HasIndex("manifest_id")
                                        .IsUnique();

                                    b2.ToTable("manifest_required_statement", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Label", "Label", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Language")
                                                .HasMaxLength(35)
                                                .HasColumnType("character varying(35)")
                                                .HasColumnName("language");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<Guid>("required_statement_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("required_statement_id");

                                            b3.ToTable("manifest_required_statement_labels", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("required_statement_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Description", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Language")
                                                .HasMaxLength(35)
                                                .HasColumnType("character varying(35)")
                                                .HasColumnName("language");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<Guid>("required_statement_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("required_statement_id");

                                            b3.ToTable("manifest_required_statement_values", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("required_statement_id");
                                        });

                                    b2.Navigation("Label");

                                    b2.Navigation("Value");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.SeeAlso", "SeeAlso", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Format")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("format");

                                    b2.Property<string>("Label")
                                        .HasColumnType("text")
                                        .HasColumnName("label");

                                    b2.Property<string>("Profile")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("profile");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_see_also", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Properties.Description", "Summary", b2 =>
                                {
                                    b2.Property<Guid>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("row_id");

                                    b2.Property<string>("Language")
                                        .HasMaxLength(35)
                                        .HasColumnType("character varying(35)")
                                        .HasColumnName("language");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("value");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RowId");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("manifest_summaries", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsOne("IIIF.Manifests.Serializer.Properties.Thumbnail", "Thumbnail", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("id");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Format")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("format");

                                    b2.Property<int?>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("height");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<int?>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("width");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id")
                                        .IsUnique();

                                    b2.ToTable("manifest_thumbnail", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");
                                });

                            b1.OwnsMany("IIIF.Manifests.Serializer.Nodes.Structure", "Structures", b2 =>
                                {
                                    b2.Property<string>("Id")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("iiif_id");

                                    b2.Property<string>("AccompanyingCanvas")
                                        .HasColumnType("jsonb")
                                        .HasColumnName("range_accompanying_canvas");

                                    b2.Property<string>("Context")
                                        .IsRequired()
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("context");

                                    b2.Property<string>("Items")
                                        .IsRequired()
                                        .HasColumnType("jsonb")
                                        .HasColumnName("items");

                                    b2.Property<string>("Rights")
                                        .HasColumnType("text")
                                        .HasColumnName("rights");

                                    b2.Property<string>("StartCanvas")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("start_canvas");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<string>("ViewingDirection")
                                        .HasColumnType("text")
                                        .HasColumnName("viewing_direction");

                                    b2.Property<Guid>("manifest_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("manifest_id");

                                    b2.ToTable("ranges", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("manifest_id");

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Behavior", "Behavior", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_behavior", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Homepage", "Homepage", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<string>("Label")
                                                .HasColumnType("text")
                                                .HasColumnName("label");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_homepage", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Label", "Label", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Language")
                                                .HasMaxLength(35)
                                                .HasColumnType("character varying(35)")
                                                .HasColumnName("language");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_labels", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsOne("IIIF.Manifests.Serializer.Properties.Logo", "Logo", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<int?>("Height")
                                                .HasColumnType("integer")
                                                .HasColumnName("height");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<int?>("Width")
                                                .HasColumnType("integer")
                                                .HasColumnName("width");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id")
                                                .IsUnique();

                                            b3.ToTable("range_logo", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.MetadataProperty.Metadata", "Metadata", b3 =>
                                        {
                                            b3.Property<string>("Label")
                                                .HasColumnType("text")
                                                .HasColumnName("label");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Label");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_metadata", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.MetadataProperty.MetadataValue.MetadataValue", "Value", b4 =>
                                                {
                                                    b4.Property<Guid>("RowId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("uuid")
                                                        .HasColumnName("row_id");

                                                    b4.Property<string>("Language")
                                                        .HasMaxLength(35)
                                                        .HasColumnType("character varying(35)")
                                                        .HasColumnName("language");

                                                    b4.Property<string>("Value")
                                                        .IsRequired()
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("value");

                                                    b4.Property<string>("metadata_label")
                                                        .HasColumnType("text");

                                                    b4.HasKey("RowId");

                                                    b4.HasIndex("metadata_label");

                                                    b4.ToTable("range_metadata_values", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("metadata_label");
                                                });

                                            b3.Navigation("Value");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.PartOf", "PartOf", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_part_of", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Provider", "Provider", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_provider", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.Homepage", "Homepage", b4 =>
                                                {
                                                    b4.Property<string>("Id")
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("id");

                                                    b4.Property<string>("Context")
                                                        .IsRequired()
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("context");

                                                    b4.Property<string>("Format")
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("format");

                                                    b4.Property<string>("Label")
                                                        .HasColumnType("text")
                                                        .HasColumnName("label");

                                                    b4.Property<string>("Type")
                                                        .HasMaxLength(100)
                                                        .HasColumnType("character varying(100)")
                                                        .HasColumnName("type");

                                                    b4.Property<string>("provider_id")
                                                        .HasColumnType("character varying(2048)");

                                                    b4.HasKey("Id");

                                                    b4.HasIndex("provider_id");

                                                    b4.ToTable("range_provider_homepages", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("provider_id");
                                                });

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.Label", "Label", b4 =>
                                                {
                                                    b4.Property<Guid>("RowId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("uuid")
                                                        .HasColumnName("row_id");

                                                    b4.Property<string>("Language")
                                                        .HasMaxLength(35)
                                                        .HasColumnType("character varying(35)")
                                                        .HasColumnName("language");

                                                    b4.Property<string>("Value")
                                                        .IsRequired()
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("value");

                                                    b4.Property<string>("provider_id")
                                                        .HasColumnType("character varying(2048)");

                                                    b4.HasKey("RowId");

                                                    b4.HasIndex("provider_id");

                                                    b4.ToTable("range_provider_labels", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("provider_id");
                                                });

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.Logo", "Logo", b4 =>
                                                {
                                                    b4.Property<string>("Id")
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("id");

                                                    b4.Property<string>("Context")
                                                        .IsRequired()
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("context");

                                                    b4.Property<string>("Format")
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("format");

                                                    b4.Property<int?>("Height")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("height");

                                                    b4.Property<string>("Type")
                                                        .HasMaxLength(100)
                                                        .HasColumnType("character varying(100)")
                                                        .HasColumnName("type");

                                                    b4.Property<int?>("Width")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("width");

                                                    b4.Property<string>("provider_id")
                                                        .HasColumnType("character varying(2048)");

                                                    b4.HasKey("Id");

                                                    b4.HasIndex("provider_id");

                                                    b4.ToTable("range_provider_logos", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("provider_id");
                                                });

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.SeeAlso", "SeeAlso", b4 =>
                                                {
                                                    b4.Property<string>("Id")
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("id");

                                                    b4.Property<string>("Context")
                                                        .IsRequired()
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("context");

                                                    b4.Property<string>("Format")
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("format");

                                                    b4.Property<string>("Label")
                                                        .HasColumnType("text")
                                                        .HasColumnName("label");

                                                    b4.Property<string>("Profile")
                                                        .HasMaxLength(2048)
                                                        .HasColumnType("character varying(2048)")
                                                        .HasColumnName("profile");

                                                    b4.Property<string>("Type")
                                                        .HasMaxLength(100)
                                                        .HasColumnType("character varying(100)")
                                                        .HasColumnName("type");

                                                    b4.Property<string>("provider_id")
                                                        .HasColumnType("character varying(2048)");

                                                    b4.HasKey("Id");

                                                    b4.HasIndex("provider_id");

                                                    b4.ToTable("range_provider_see_also", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("provider_id");
                                                });

                                            b3.Navigation("Homepage");

                                            b3.Navigation("Label");

                                            b3.Navigation("Logo");

                                            b3.Navigation("SeeAlso");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Rendering", "Rendering", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<string>("Label")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("label");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_rendering", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsOne("IIIF.Manifests.Serializer.Properties.RequiredStatement", "RequiredStatement", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("range_id")
                                                .IsUnique();

                                            b3.ToTable("range_required_statement", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.Label", "Label", b4 =>
                                                {
                                                    b4.Property<Guid>("RowId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("uuid")
                                                        .HasColumnName("row_id");

                                                    b4.Property<string>("Language")
                                                        .HasMaxLength(35)
                                                        .HasColumnType("character varying(35)")
                                                        .HasColumnName("language");

                                                    b4.Property<string>("Value")
                                                        .IsRequired()
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("value");

                                                    b4.Property<Guid>("required_statement_id")
                                                        .HasColumnType("uuid");

                                                    b4.HasKey("RowId");

                                                    b4.HasIndex("required_statement_id");

                                                    b4.ToTable("range_required_statement_labels", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("required_statement_id");
                                                });

                                            b3.OwnsMany("IIIF.Manifests.Serializer.Properties.Description", "Value", b4 =>
                                                {
                                                    b4.Property<Guid>("RowId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("uuid")
                                                        .HasColumnName("row_id");

                                                    b4.Property<string>("Language")
                                                        .HasMaxLength(35)
                                                        .HasColumnType("character varying(35)")
                                                        .HasColumnName("language");

                                                    b4.Property<string>("Value")
                                                        .IsRequired()
                                                        .HasMaxLength(255)
                                                        .HasColumnType("character varying(255)")
                                                        .HasColumnName("value");

                                                    b4.Property<Guid>("required_statement_id")
                                                        .HasColumnType("uuid");

                                                    b4.HasKey("RowId");

                                                    b4.HasIndex("required_statement_id");

                                                    b4.ToTable("range_required_statement_values", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("required_statement_id");
                                                });

                                            b3.Navigation("Label");

                                            b3.Navigation("Value");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.SeeAlso", "SeeAlso", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<string>("Label")
                                                .HasColumnType("text")
                                                .HasColumnName("label");

                                            b3.Property<string>("Profile")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("profile");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_see_also", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsMany("IIIF.Manifests.Serializer.Properties.Description", "Summary", b3 =>
                                        {
                                            b3.Property<Guid>("RowId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("row_id");

                                            b3.Property<string>("Language")
                                                .HasMaxLength(35)
                                                .HasColumnType("character varying(35)")
                                                .HasColumnName("language");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("value");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("RowId");

                                            b3.HasIndex("range_id");

                                            b3.ToTable("range_summaries", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.OwnsOne("IIIF.Manifests.Serializer.Properties.Thumbnail", "Thumbnail", b3 =>
                                        {
                                            b3.Property<string>("Id")
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("id");

                                            b3.Property<string>("Context")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .HasColumnType("character varying(2048)")
                                                .HasColumnName("context");

                                            b3.Property<string>("Format")
                                                .HasMaxLength(255)
                                                .HasColumnType("character varying(255)")
                                                .HasColumnName("format");

                                            b3.Property<int?>("Height")
                                                .HasColumnType("integer")
                                                .HasColumnName("height");

                                            b3.Property<string>("Type")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)")
                                                .HasColumnName("type");

                                            b3.Property<int?>("Width")
                                                .HasColumnType("integer")
                                                .HasColumnName("width");

                                            b3.Property<string>("range_id")
                                                .HasColumnType("character varying(2048)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("range_id")
                                                .IsUnique();

                                            b3.ToTable("range_thumbnail", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("range_id");
                                        });

                                    b2.Navigation("Behavior");

                                    b2.Navigation("Homepage");

                                    b2.Navigation("Label");

                                    b2.Navigation("Logo");

                                    b2.Navigation("Metadata");

                                    b2.Navigation("PartOf");

                                    b2.Navigation("Provider");

                                    b2.Navigation("Rendering");

                                    b2.Navigation("RequiredStatement");

                                    b2.Navigation("SeeAlso");

                                    b2.Navigation("Summary");

                                    b2.Navigation("Thumbnail");
                                });

                            b1.Navigation("Behavior");

                            b1.Navigation("Homepage");

                            b1.Navigation("Label");

                            b1.Navigation("Logo");

                            b1.Navigation("Metadata");

                            b1.Navigation("PartOf");

                            b1.Navigation("Provider");

                            b1.Navigation("Rendering");

                            b1.Navigation("RequiredStatement");

                            b1.Navigation("SeeAlso");

                            b1.Navigation("Structures");

                            b1.Navigation("Summary");

                            b1.Navigation("Thumbnail");
                        });

                    b.Navigation("Manifest")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
